### PR TITLE
Delete button and Licensing

### PR DESCRIPTION
**Pull request by NickEngmann**
Gonna start by admitting, this is definitely a hack. [Neither SimpleHTTPServer/BaseHTTPServer have a class that can handle do_Delete()](https://docs.python.org/3/library/http.server.html), so to get around that I am simply using a post request.

During the POST request method I have now included logic to see if the delete button was pressed, and if so I grab the name of the file and "sudo rm -f (filename)". Works like a charm.

Also took the time to clean up some of the styling; including adding the wallpaper to all the sub screens, and fixing the references to this Repository.

image

### CODE REVIEW

**Comment by NickEngmann** [comment]
How the Delete Buttons Look Like
53792608_296893407655478_815586608446177280_n

**Comment by NickEngmann** [comment]
How the Successful Delete Results Page Looks Like:
54255317_674286002989096_8665448384875724800_n

**Comment by Halcy0nic** [comment]
Thanks Nick.  One thing we might have to address with the POST request is this: https://0day.work/finding-an-arbitrary-file-upload-vulnerability-in-a-filesharing-script/

I'll take a deeper look into it to see if any of our changes are still affected by this but for the time being.  We can do another PR for the fix if I find it's an issue

**Comment by NickEngmann** [comment]
True, with the current implementation someone could upload a file called "../../etc/sudoers"

The file would exist within /var/www/SUBZero
var
--www
---SUBZero
---- ../../etc/sudoers

But if someone tried to delete that file it would delete ../../etc/sudoers

If we wanted to we could implement a fix that prevents uploading file names that include the "/" symbol.

**Comment by NickEngmann** [comment]
I'll go ahead and merge this but make an Issue concerning validating filenames

**Comment by Halcy0nic** [comment]
I fixed it.  Super Easy

**Comment by NickEngmann** [comment]
image

**Comment by Halcy0nic** [comment]
You can go ahead and merge

**Pull request merged**
